{% set version = "1.38.26" %}

package:
  name: binaryen
  version: {{ version }}

source:
  fn: binaryen-{{ version }}.tar.gz
  url: https://github.com/WebAssembly/binaryen/archive/{{ version }}.tar.gz
  sha256: b32376e3b2074a4ad60da618e2b2026054922f5fa8121b71b9658d8e5de71647

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - nodejs
    - python 2.7
  host:

test:
  commands:
    - wasm-shell --help
    - wasm-opt --help
    - wasm-merge --help
    - wasm-metadce --help
    - asm2wasm --help
    - wasm2js --help
    - wasm-emscripten-finalize --help
    - wasm-as --help
    - wasm-dis --help
    - wasm-ctor-eval --help
    - wasm-reduce --help

about:
  home: https://github.com/WebAssembly/binaryen
  license: Apache 2.0
  license_file: LICENSE
  summary: Compiler infrastructure and toolchain library for WebAssembly, in C++

extra:
  recipe-maintainers:
    - jakirkham
