{% set version = "1.38.11" %}

package:
  name: binaryen
  version: {{ version }}

source:
  fn: binaryen-{{ version }}.tar.gz
  url: https://github.com/WebAssembly/binaryen/archive/{{ version }}.tar.gz
  sha256: 414a3dd59876d86095aa91970dc1b2a8a3aafacc7e38388768b8bae4b320bd00

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - nodejs
    - python 2.7
  host:

test:
  commands:
    - wasm-shell --help
    - wasm-opt --help
    - wasm-merge --help
    - wasm-metadce --help
    - asm2wasm --help
    - wasm2asm --help
    - wasm-emscripten-finalize --help
    - wasm-as --help
    - wasm-dis --help
    - wasm-ctor-eval --help
    - wasm-reduce --help

    - test -f "${PREFIX}/lib/libbinaryen${SHLIB_EXT}"   # [unix]
    - if not exist %LIBRARY_BIN%\\binaryen.dll" exit 1  # [win]

about:
  home: https://github.com/WebAssembly/binaryen
  license: Apache 2.0
  license_file: LICENSE
  summary: Compiler infrastructure and toolchain library for WebAssembly, in C++

extra:
  recipe-maintainers:
    - jakirkham
